org.gradle.java.home=C:/Program Files/Java/jdk-21.0.10
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false

minecraft_version=1.21.2
yarn_mappings=1.21.2+build.1
loader_version=0.19.2

mod_version=1.0.0
maven_group=com.theobald
archives_base_name=fight-camera

fabric_version=0.106.1+1.21.2